export const robots = [
	{
		id: 1,
		name: 'Charlize Fraser',
		username: 'SeaEff',
		email: 'CharlizetheDivorced@april.biz',
	},
	{
		id: 2,
		name: 'Habibah Gallagher',
		username: 'Entertainingmuffin',
		email: 'GallaghertheBalaguer@hannah.biz',
	},
	{
		id: 3,
		name: 'Kennedy Sparrow',
		username: 'Kookykennedy',
		email: 'Narrowsparrow@yesenia.net',
	},
	{
		id: 4,
		name: 'Jeanne Burn',
		username: 'Burnthefern',
		email: 'Burnthefern@kooky.org',
	},
	{
		id: 5,
		name: 'Jacqueline Cherry',
		username: 'Cherrya',
		email: 'Arbitrarycherry@gmails.com',
	},
	{
		id: 6,
		name: 'Enoch Barlow',
		username: 'Gobarlow',
		email: 'Blowbarlow@yesenia.org',
	},
	{
		id: 7,
		name: 'Stanislaw Wang',
		username: 'Fangwang',
		email: 'Fangwang@hottiemail.net',
	},
	{
		id: 8,
		name: 'Tye Kouma',
		username: 'Lietie',
		email: 'Kouminator@gmails.com',
	},
	{
		id: 9,
		name: 'Izabela Draper',
		username: 'Draperthevapor',
		email: 'Vapor54@hottiemail.org',
	},
	{
		id: 10,
		name: 'Mohammod Gilmour',
		username: 'Emgee',
		email: 'Emgee@yoohoo.net',
	},
	{
		id: 11,
		name: 'Terrence Roberts',
		username: 'Terrencetheforberence',
		email: 'Robomeister@bree.biz',
	},
	{
		id: 12,
		name: 'Kobi Barrera',
		username: 'Kobob',
		email: 'Kobob@kobob.org',
	},
	{
		id: 13,
		name: 'Safiyyah Lane',
		username: 'Trainlane',
		email: 'Trainlane@finalsaya.org',
	},
	{
		id: 14,
		name: 'Kaydon Lucas',
		username: 'Kaydonthemaiden',
		email: 'Maiden23439@thebobs.com',
	},
	{
		id: 15,
		name: 'Zack Sadler',
		username: 'Zackthemack',
		email: 'Snackymacky@sadlerenterprises.biz',
	},
	{
		id: 16,
		name: 'Renesmae Appleton',
		username: 'Rottenapples',
		email: 'Theapplesarerottenduh@lolhackers.net',
	},
	{
		id: 17,
		name: 'Fergus Preece',
		username: 'Preecethepiece',
		email: 'Getapieceofpreece@hottiemail.net',
	},
	{
		id: 18,
		name: 'Rhia Watts',
		username: 'Dotswatts',
		email: 'Dotswatts@kimberly.nets',
	},
	{
		id: 19,
		name: 'Kylo Durham',
		username: 'Slamdurham',
		email: 'Slammedbydurham@hackerlols.biz',
	},
	{
		id: 20,
		name: 'Adeel Armstrong',
		username: 'Armstrongthestrong',
		email: 'Strongarmstrongs@bigmusclymuscles.com',
	},
]